BEGIN;

DROP TABLE IF EXISTS "cart",
"cart_has_collab",
"cart_has_tag",
"color",
"kanban",
"kanban_has_collab",
"list",
"list_has_tag",
"role",
"status",
"tag",
"utilisateur";

/* ON DELETE CASCADE */
CREATE TABLE IF NOT EXISTS "cart" (
    "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "name" text NOT NULL,
    "position" integer NOT NULL,
    "deadline" timestamp with time zone NULL,
    "description" text NULL,
    "attachment" text NULL,
    "pinned" integer NOT NULL,
    "list_id" integer NOT NULL,
    "status_id" integer NOT NULL,
    "color_id" integer NOT NULL,
    "created_at" timestamp with time zone NOT NULL DEFAULT now(),
    "updated_at" timestamp with time zone NULL
  );

/* */
CREATE TABLE IF NOT EXISTS "cart_has_collab" (
    "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "utilisateur_id" integer NOT NULL,
    "cart_id" integer NOT NULL,
    "created_at" timestamp with time zone NOT NULL DEFAULT now(),
  );

/* */
CREATE TABLE IF NOT EXISTS "cart_has_tag" (
    "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "cart_id" integer NOT NULL,
    "tag_id" integer NOT NULL,
    "created_at" timestamp with time zone NOT NULL DEFAULT now(),
  );

/* */
CREATE TABLE IF NOT EXISTS "color" (
    "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "name" text NOT NULL,
    "created_at" timestamp with time zone NOT NULL DEFAULT now(),
    "updated_at" timestamp with time zone NULL
  );

/* */
CREATE TABLE IF NOT EXISTS "kanban" (
    "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "owner_id" integer NOT NULL,
    "name" text NOT NULL,
    "description" text NULL,
    "created_at" timestamp with time zone NOT NULL DEFAULT now(),
    "updated_at" timestamp with time zone NULL
  );

/* */
CREATE TABLE IF NOT EXISTS "kanban_has_collab" (
    "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "kanban_id" integer NULL,
    "utilisateur_id" integer NULL,
    "created_at" timestamp with time zone NOT NULL DEFAULT now(),
  );

/* */
CREATE TABLE IF NOT EXISTS "list" (
    "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "kanban_id" integer NOT NULL,
    "name" text NOT NULL,
    "status_id" integer NOT NULL,
    "description" text NULL,
    "position" integer NOT NULL,
    "pinned" integer NOT NULL,
    "color_id" integer NOT NULL,
    "created_at" timestamp with time zone NOT NULL DEFAULT now(),
    "updated_at" timestamp with time zone NULL
  );

/* */
CREATE TABLE IF NOT EXISTS "list_has_tag" (
    "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "list_id" integer NOT NULL,
    "tag_id" integer NOT NULL,
    "created_at" timestamp with time zone NOT NULL DEFAULT now(),
  );

/* */
CREATE TABLE IF NOT EXISTS "role" (
    "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "name" text NOT NULL,
    "created_at" timestamp with time zone NOT NULL DEFAULT now(),
    "updated_at" timestamp with time zone NULL
  );

/* */
CREATE TABLE IF NOT EXISTS "status" (
    "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "name" text NOT NULL,
    "created_at" timestamp with time zone NOT NULL DEFAULT now(),
    "updated_at" timestamp with time zone NULL
  );

/* */
CREATE TABLE IF NOT EXISTS "tag" (
    "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "name" text NULL,
    "created_at" timestamp with time zone NOT NULL DEFAULT now(),
    "updated_at" timestamp with time zone NULL
  );

/* */
CREATE TABLE IF NOT EXISTS "utilisateur" (
    "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "firstname" text NOT NULL,
    "lastname" text NOT NULL,
    "email" text NOT NULL,
    "password" text NOT NULL,
    "role_id" integer NOT NULL,
    "created_at" timestamp with time zone NOT NULL DEFAULT now(),
    "updated_at" timestamp with time zone NULL
  );


COMMIT;