BEGIN;

DROP TABLE IF EXISTS "cart",
"cart_has_collab",
"cart_has_tag",
"color",
"kanban",
"kanban_has_collab",
"list",
"list_has_tag",
"role",
"status",
"tag",
"utilisateur";

/*  */
CREATE TABLE IF NOT EXISTS "cart" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "name" TEXT NOT NULL,
    "position" INTEGER NOT NULL DEFAULT 0,
    "deadline" TIMESTAMP with time zone NULL DEFAULT now(),
    "description" TEXT NULL,
    "attachment" TEXT NULL,
    "pinned" INTEGER NOT NULL DEFAULT 0,
    "list_id" INTEGER NOT NULL,
    "status_id" INTEGER NOT NULL DEFAULT 1,
    "color_id" INTEGER NOT NULL DEFAULT 1,
    "created_at" TIMESTAMP with time zone NOT NULL DEFAULT now(),
    "updated_at" TIMESTAMP with time zone NULL
  );

/* */
CREATE TABLE IF NOT EXISTS "cart_has_collab" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "utilisateur_id" INTEGER NOT NULL,
    "cart_id" INTEGER NOT NULL,
    "created_at" TIMESTAMP with time zone NOT NULL DEFAULT now()
  );

/* */
CREATE TABLE IF NOT EXISTS "cart_has_tag" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "cart_id" INTEGER NOT NULL,
    "tag_id" INTEGER NOT NULL,
    "created_at" TIMESTAMP with time zone NOT NULL DEFAULT now()
  );

/* */
CREATE TABLE IF NOT EXISTS "color" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "name" TEXT NOT NULL,
    "created_at" TIMESTAMP with time zone NOT NULL DEFAULT now(),
    "updated_at" TIMESTAMP with time zone NULL
  );

/* */
CREATE TABLE IF NOT EXISTS "kanban" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "owner_id" INTEGER NOT NULL,
    "name" TEXT NOT NULL,
    "description" TEXT NULL,
    "created_at" TIMESTAMP with time zone NOT NULL DEFAULT now(),
    "updated_at" TIMESTAMP with time zone NULL
  );

/* */
CREATE TABLE IF NOT EXISTS "kanban_has_collab" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "kanban_id" INTEGER NULL,
    "utilisateur_id" INTEGER NULL,
    "created_at" TIMESTAMP with time zone NOT NULL DEFAULT now()
  );

/* */
CREATE TABLE IF NOT EXISTS "list" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "kanban_id" INTEGER NOT NULL,
    "name" TEXT NOT NULL,
    "status_id" INTEGER NOT NULL DEFAULT 1,
    "description" TEXT NULL,
    "position" INTEGER NOT NULL DEFAULT 0,
    "pinned" INTEGER NOT NULL DEFAULT 0,
    "color_id" INTEGER NOT NULL DEFAULT 1,
    "created_at" TIMESTAMP with time zone NOT NULL DEFAULT now(),
    "updated_at" TIMESTAMP with time zone NULL
  );

/* */
CREATE TABLE IF NOT EXISTS "list_has_tag" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "list_id" INTEGER NOT NULL,
    "tag_id" INTEGER NOT NULL,
    "created_at" TIMESTAMP with time zone NOT NULL DEFAULT now()
  );

/* */
CREATE TABLE IF NOT EXISTS "role" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "name" TEXT NOT NULL,
    "created_at" TIMESTAMP with time zone NOT NULL DEFAULT now(),
    "updated_at" TIMESTAMP with time zone NULL
  );

/* */
CREATE TABLE IF NOT EXISTS "status" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "name" TEXT NOT NULL,
    "created_at" TIMESTAMP with time zone NOT NULL DEFAULT now(),
    "updated_at" TIMESTAMP with time zone NULL
  );

/* */
CREATE TABLE IF NOT EXISTS "tag" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "name" TEXT NULL,
    "created_at" TIMESTAMP with time zone NOT NULL DEFAULT now(),
    "updated_at" TIMESTAMP with time zone NULL
  );

/* */
CREATE TABLE IF NOT EXISTS "utilisateur" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "firstname" TEXT NOT NULL,
    "lastname" TEXT NOT NULL,
    "email" TEXT NOT NULL,
    "password" TEXT NOT NULL,
    "role_id" INTEGER NOT NULL,
    "created_at" TIMESTAMP with time zone NOT NULL DEFAULT now(),
    "updated_at" TIMESTAMP with time zone NULL
  );


COMMIT;